src/SampleWebApplication/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SampleWebApplication.Data;
using SampleWebApplication.Models.Customers;

namespace SampleWebApplication.Controllers
{
    public class CustomersController : BaseController
    {
        public CustomersController(ApplicationDbContext context)
        {
            this.Context = context;
        }

        public ApplicationDbContext Context { get; set; }

        [HttpGet]
        public IActionResult Index(IndexModel model)
        {
            model.ItemCount = Context.Customer.Count();

            model.Items = Context.Customer
                .Include(c => c.Country)
                .OrderBy(c => c.Id)
                .Skip((model.Page - 1) * model.PageSize)
                .Take(model.PageSize)
                .ToArray();

            return View(model);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var model = new UpdateModel();
            model.Item = Context.Customer
                .Include(c => c.Country)
                .SingleOrDefault(c => c.Id == id)
                ?? new Customer();

            return UpdateView(model);
        }

        [HttpPost]
        public IActionResult Update(UpdateModel model)
        {
            if (ModelState.IsValid)
            {
                Context.Update(model.Item);
                Context.SaveChanges();

                return Back(false);
            }
            else
            {
                return UpdateView(model);
            }
        }

        [NonAction]
        private IActionResult UpdateView(UpdateModel model)
        {
            model.Countries = Context.Country.OrderBy(c => c.Name).ToArray();

            return View("Update", model);
        }
        
        [HttpPost]
        public IActionResult Delete(UpdateModel model)
        {
            Context.Remove(model.Item);
            Context.SaveChanges();

            return Back(false);
        }
    }
}

src/SampleWebApplication/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SampleWebApplication.Data;
using SampleWebApplication.Models.Invoices;

namespace SampleWebApplication.Controllers
{
    public class InvoicesController : BaseController
    {
        public InvoicesController(ApplicationDbContext context)
        {
            this.Context = context;
        }

        public ApplicationDbContext Context { get; set; }

        [HttpGet]
        public IActionResult Index(IndexModel model)
        {
            if (model.CustomerId.HasValue)
            {
                model.ItemCount = Context.Invoice.Where(i => i.CustomerId == model.CustomerId).Count();

                model.Items = Context.Invoice
                    .Include(i => i.Customer)
                    .Where(i => i.CustomerId == model.CustomerId)
                    .OrderBy(c => c.Id)
                    .Skip((model.Page - 1) * model.PageSize)
                    .Take(model.PageSize)
                    .ToArray();
            }
            else
            {
                model.ItemCount = Context.Invoice.Count();

                model.Items = Context.Invoice
                    .Include(i => i.Customer)
                    .OrderBy(c => c.Id)
                    .Skip((model.Page - 1) * model.PageSize)
                    .Take(model.PageSize)
                    .ToArray();
            }

            return View("Index", model);
        }

        [HttpPost]
        public IActionResult SetPaid(IndexModel model)
        {
            ModelState.Clear();
            System.Threading.Thread.Sleep(200);
            foreach (var item in Context.Invoice.Where(i => model.Selection.Contains(i.Id)))
            {
                item.Status = InvoiceStatus.Paid;
            }
            Context.SaveChanges();

            return Index(model);
        }

        [HttpPost]
        public IActionResult SetAwaiting(IndexModel model)
        {
            ModelState.Clear();
            System.Threading.Thread.Sleep(200);
            foreach (var item in Context.Invoice.Where(i => model.Selection.Contains(i.Id)))
            {
                item.Status = InvoiceStatus.AwaitingPayment;
            }
            Context.SaveChanges();

            return Index(model);
        }

        [HttpGet]
        public IActionResult Update(int id, int customerId = 0)
        {
            var model = new UpdateModel();
            model.Item = Context.Invoice
                .Include(c => c.Customer).ThenInclude(c => c.Country)
                .Include(c => c.Lines).ThenInclude(l => l.Product)
                .SingleOrDefault(c => c.Id == id)
                ?? new Invoice() { CustomerId = customerId, Date = DateTime.Now.Date };

            return UpdateView(model);
        }

        [HttpPost]
        public IActionResult AddLine(UpdateModel model)
        {
            ModelState.Clear();

            model.Item.With(model.NewLine.Quantity, Context.Product.Find(model.NewLine.ProductId));

            return UpdateView(model);
        }

        [HttpPost]
        public IActionResult RemoveLine(UpdateModel model, int index)
        {
            ModelState.Clear();

            model.Item.Lines.RemoveAt(index);

            return UpdateView(model);
        }

        [HttpPost]
        public IActionResult Update(UpdateModel model)
        {
            if (ModelState.IsValid)
            {
                var persistedInvoice = Context.Invoice
                    .Include(i => i.Lines)
                    .SingleOrDefault(i => i.Id == model.Item.Id);
                if (persistedInvoice == null)
                {
                    persistedInvoice = new Invoice();
                    Context.Invoice.Add(persistedInvoice);
                }
                Context.Entry(persistedInvoice).CurrentValues.SetValues(model.Item);
                foreach (var line in model.Item.Lines)
                {
                    line.InvoiceId = persistedInvoice.Id;
                    var persistedInvoiceLine = persistedInvoice.Lines.SingleOrDefault(l => l.Id == line.Id && line.Id != 0);
                    if (persistedInvoiceLine == null)
                    {
                        persistedInvoiceLine = new InvoiceLine() { Invoice = persistedInvoice };
                        Context.InvoiceLine.Add(persistedInvoiceLine);
                    }
                    Context.Entry(persistedInvoiceLine).CurrentValues.SetValues(line);
                }
                foreach (var line in persistedInvoice.Lines.Where(l => !model.Item.Lines.Select(ll => ll.Id).Contains(l.Id)))
                {
                    Context.Remove(line);
                }
                Context.SaveChanges();

                return Back(false);
            }
            else
            {
                return UpdateView(model);
            }
        }

        [NonAction]
        private IActionResult UpdateView(UpdateModel model)
        {
            model.Item.Customer = Context.Customer.Include(c => c.Country).SingleOrDefault(c => c.Id == model.Item.CustomerId);
            model.NewLine = new InvoiceLine();
            model.Customers = Context.Customer.OrderBy(p => p.Name).ToArray();
            model.Products = Context.Product.OrderBy(p => p.Label).ToArray();

            return View("Update", model);
        }

        [HttpPost]
        public IActionResult Delete(UpdateModel model)
        {
            Context.Remove(model.Item);
            Context.SaveChanges();

            return Back(false);
        }
    }
}

src/SampleWebApplication/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Headers;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SampleWebApplication.Data;
using SampleWebApplication.Models.Products;

namespace SampleWebApplication.Controllers
{
    public class ProductsController : BaseController
    {
        public ProductsController(ApplicationDbContext context)
        {
            this.Context = context;
        }

        public ApplicationDbContext Context { get; set; }

        [HttpGet]
        public IActionResult AutoComplete(string value, string listid = null)
        {
            // Retrieve list of items:
            var model = Context.Product.Where(p => p.Label.Contains(value)).Select(p => p.Label).OrderBy(l => l).ToList();
            if (model.Count == 1 && model[0] == value) model.Clear();

            // Return datalist:
            var html = new StringBuilder();
            if (listid != null) html.Append($"<datalist id=\"{listid}\">");
            foreach (var item in model)
            {
                html.Append("<option value=\"");
                html.Append(HttpUtility.HtmlEncode(item));
                html.Append("\">");
            }
            if (listid != null) html.Append("</datalist>");
            return Content(html.ToString(), "text/html");
        }

        [HttpGet]
        public IActionResult Index(IndexModel model)
        {
            model.ItemCount = Context.Product
                .Where(p => p.Label.Contains(model.Query ?? ""))
                .Count();

            model.Items = Context.Product
                .Where(p => p.Label.Contains(model.Query ?? ""))
                .OrderBy(c => c.Id)
                .Skip((model.Page - 1) * model.PageSize)
                .Take(model.PageSize)
                .ToArray();

            return View("Index", model);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var model = new UpdateModel();
            model.Item = Context.Product
                .SingleOrDefault(c => c.Id == id)
                ?? new Product();

            return UpdateView(model);
        }

        [HttpPost]
        public IActionResult Update(UpdateModel model)
        {
            if (ModelState.IsValid)
            {
                Context.Update(model.Item);
                Context.SaveChanges();

                Response.Headers["X-Sircl-Toastr"] = $"success|Your changes to <i>{HttpUtility.HtmlEncode(model.Item.Label)}</i> have now been saved.|Product changes saved";

                return Back(false);
            }
            else
            {
                return UpdateView(model);
            }
        }

        [NonAction]
        private IActionResult UpdateView(UpdateModel model)
        {
            return View("Update", model);
        }

        [HttpPost]
        public IActionResult Delete(UpdateModel model)
        {
            Context.Remove(model.Item);
            Context.SaveChanges();

            return Back(false);
        }

        public IActionResult List()
        {
            Thread.Sleep(300);

            var model = new ListModel();
            model.Products.AddRange(Context.Product);

            return Json(model);
        }
    }
}

src/SampleWebApplication/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SampleWebApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SampleWebApplication.Controllers
{
    public class ToDoController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            var model = new ToDoListModel();
            model.NewItems = Program.ToDoLanes[0];
            model.BusyItems = Program.ToDoLanes[1];
            model.DoneItems = Program.ToDoLanes[2];

            return ViewIndex(model, true);
        }

        [HttpPost]
        public IActionResult Submit(ToDoListModel model)
        {
            return ViewIndex(model, true);
        }

        [HttpPost]
        public IActionResult Drop(ToDoListModel model, int targetZone)
        {
            var dropdata = model.DropData.Split(',');
            var sourceZone = Int32.Parse(dropdata[0]);
            var sourceIndex = Int32.Parse(dropdata[1]);

            ToDoItem item = null;
            switch (sourceZone)
            {
                case 0:
                    item = model.NewItems[sourceIndex];
                    model.NewItems.RemoveAt(sourceIndex);
                    break;
                case 1:
                    item = model.BusyItems[sourceIndex];
                    model.BusyItems.RemoveAt(sourceIndex);
                    break;
                case 2:
                    item = model.DoneItems[sourceIndex];
                    model.DoneItems.RemoveAt(sourceIndex);
                    break;
            }

            switch (targetZone)
            {
                case 0:
                    model.NewItems.Add(item);
                    break;
                case 1:
                    model.BusyItems.Add(item);
                    break;
                case 2:
                    model.DoneItems.Add(item);
                    break;
            }

            return ViewIndex(model, true);
        }

        [HttpPost]
        public IActionResult Add(ToDoListModel model)
        {
            model.NewItems.Add(model.NewItem);
            model.NewItem = null;

            return ViewIndex(model, true);
        }

        [HttpPost]
        public IActionResult Save(ToDoListModel model)
        {
            if (ModelState.IsValid)
            {
                Program.ToDoLanes = new List<List<ToDoItem>>() 
                {
                    model.NewItems,
                    model.BusyItems,
                    model.DoneItems
                };
            }

            return ViewIndex(model, false);
        }

        private IActionResult ViewIndex(ToDoListModel model, bool clearModelstate)
        {
            if (clearModelstate) ModelState.Clear();
            return View("Index", model);
        }

        [HttpPost]
        public IActionResult DropFiles(List<IFormFile> files, List<string> filenames = null)
        {
            filenames ??= new List<string>();
            foreach (var item in files)
            {
                filenames.Add(item.FileName);
            }

            return View("Index_FileList", filenames);
        }
    }
}

src/SampleWebApplication/Views/Shared/_Layout.cshtml
@if (this.Context.Request.Headers["X-Sircl-Request-Type"] == "Partial")
{
    <script>if (typeof sircl === 'undefined') { location.reload(); }</script>
    @:@RenderBody()
    return;
}
@if (this.Context.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
{
    <script>if (typeof sircl === 'undefined') { location.reload(); }</script>
    @:@RenderBody()
    return;
}
@{
    var minified = false;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sircl2 Samples &amp; Tests</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    @if (minified)
    {
        <link href="~/lib/sircl-src-new/sircl-bundled.min.css" rel="stylesheet" />
    }
    else
    {
        <link href="~/lib/sircl-src-new/sircl.css" rel="stylesheet" type="text/css" />
        <link href="~/lib/sircl-src-new/sircl-contextmenu.css" rel="stylesheet" type="text/css" />
    }
</head>
<body class="ondropfile-ignore">

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sircl2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" ifroute-setactive="^\/($|Home(\/|$))">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="IndexDelayed">Home</a>
                        </li>
                        <li class="nav-item" ifroute-setactive="^\/Home\/Playground(\/|$)">
                            <a class="nav-link text-dark" href="/Home/Playground#pics">Play</a>
                        </li>
                        <li class="nav-item" ifroute-setactive="^\/Home\/Media(\/|$)">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Media">Media</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="PlaygroundBs5">BS5</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ProductList">Prods</a>
                        </li>
                        <li class="nav-item" ifroute-setactive="^\/ToDo(\/|$)">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="Index">ToDos</a>
                        </li>
                        <li class="nav-item" ifroute-setactive="^\/Customers(\/|$)">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item" ifroute-setactive="^\/Invoices(\/|$)">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Invoices" asp-action="Index">Invoices</a>
                        </li>
                        <li class="nav-item" ifroute-setactive="^\/Products(\/|$)">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index" onkeydown-click="Alt+P">Products <kbd>Alt+P</kbd></a>
                        </li>
                        <li class="nav-item" ifroute-setactive="^\/Privacy(\/|$)">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <div class="row">
            <div class="col">
                <div id="toasts-container" class="float-right"></div>
            </div>
        </div>

        @* <div class="contextmenu">
                <div class="nav flex-column nav-pills">
                    <a class="nav-link" href="javascript:alert('Hi !')">Say hi !</a>
                    <a class="nav-link" href="javascript:document.body.contentEditable='true'; document.designMode='on'; void 0">Edit this page</a>
                </div>
            </div> *@

        <div>
            <progress class="main-download-progress float-right" hidden></progress>
            <progress class="main-upload-progress float-left" hidden></progress><br />
        </div>
        <div class="progress main-upload-progress">
            <div class="progress-bar"></div>
        </div>
        <div class="progress main-download-progress">
            <div class="progress-bar"></div>
        </div>
        <main role="main" id="main-target-id" class="pb-3 main-target with-overlay" onload-startviewtransition source-url="." upload-progress=".main-upload-progress" download-progress=".main-download-progress">
            @RenderBody()
        </main>

    </div>

    <div id="confirm-modal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Please confirm...</h5>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" name="okButton">OK</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" onload-showmodalafter="5000" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="bs-modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h5>Welcome!</h5>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>

    <div id="back-top" class="onclick-scrolltop onscrolltop-fade" hidden>
        <i class="fas fa-chevron-circle-up"></i>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - SampleWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a><span class="d-none d-sm-inline"> - Last full page refresh: @DateTime.Now</span> <a href="history:back" class="btn btn-xs">&lt;</a> <a href="history:forward" class="btn btn-xs">&gt;</a>
        </div>
    </footer>

    <!-- Barcode polyfill: -->
    <!-- Source: https://github.com/undecaf/barcode-detector-polyfill -->
    <script src="https://cdn.jsdelivr.net/npm/@@undecaf/zbar-wasm@@0.9.15/dist/index.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@undecaf/barcode-detector-polyfill@@0.9.20/dist/index.js"></script>
    <script>
        if (!('BarcodeDetector' in window)) {
            window['BarcodeDetector'] = barcodeDetectorPolyfill.BarcodeDetectorPolyfill
        }
    </script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> *@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/lib/sortable/Sortable.js"></script>
    <script src="~/lib/font-awesome/js/all.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/qrious/4.0.2/qrious.min.js" integrity="sha512-pUhApVQtLbnpLtJn6DuzDD5o2xtmLJnJ7oBoMsBnzOkVkpqofGLGPaBJ6ayD2zQe3lCgCibhJBi4cj5wAxwVKA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://unpkg.com/vue@3/dist/vue.global.prod.js"></script>
    <script src="~/lib/long-press-event/long-press-event.js"></script>
    <script src="~/lib/jquery.touchswipe/jquery.touchSwipe.js"></script>
    @if (minified)
    {
        <script src="~/lib/sircl-src-new/sircl-bundled.min.js"></script>
        <script src="~/lib/sircl-src-new/sircl-bootstrap4.min.js"></script>
        <script src="~/lib/sircl-src-new/sircl-media.min.js"></script>
        <script src="~/lib/sircl-src-new/sircl-fa.min.js"></script>
        <script src="~/lib/sircl-src-new/sircl-toastr.min.js"></script>
        <script src="~/lib/sircl-src-new/sircl-sortable.min.js"></script>
        <script src="~/lib/sircl-src-new/sircl-qrious.min.js"></script>
        <script src="~/lib/sircl-src-new/sircl-vue.min.js"></script>
        <script src="~/lib/sircl-src-new/sircl-serversentevents.min.js"></script>
        <script src="~/lib/sircl-src-new/sircl-touchswipe-jquery.min.js"></script>
        <script src="~/lib/sircl-src-new/sircl-longpressevent.min.js"></script>
    }
    else
    {
        <script src="~/lib/sircl-src-new/sircl.js"></script>
        <script src="~/lib/sircl-src-new/sircl-extended.js"></script>
        <script src="~/lib/sircl-src-new/sircl-changeactions.js"></script>
        <script src="~/lib/sircl-src-new/sircl-contextmenu.js"></script>
        <script src="~/lib/sircl-src-new/sircl-bootstrap4.js"></script>
        <script src="~/lib/sircl-src-new/sircl-media.js"></script>
        <script src="~/lib/sircl-src-new/sircl-fa.js"></script>
        <script src="~/lib/sircl-src-new/sircl-toastr.js"></script>
        <script src="~/lib/sircl-src-new/sircl-sortable.js"></script>
        <script src="~/lib/sircl-src-new/sircl-qrious.js"></script>
        <script src="~/lib/sircl-src-new/sircl-vue.js"></script>
        <script src="~/lib/sircl-src-new/sircl-serversentevents.js"></script>
        <script src="~/lib/sircl-src-new/sircl-touchswipe-jquery.js"></script>
        <script src="~/lib/sircl-src-new/sircl-longpressevent.min.js"></script>
        @*<script src="~/lib/sircl-src-new/sircl-debugging.js"></script>*@
    }

    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    @*<script src="~/lib/sircl-src-new/sircl-samples-extensibility.js"></script>*@
    <script>
        $$(function () {
            $("[data-bs-toggle='popover']").popover({ container: "body" });
            $("[data-toggle='tooltip']").tooltip({ boundary: "window" });
        });
    </script>
    <script>

        sircl.addErrorHandler(function (code, message, data) {
            alert(code + ": " + message);
        });
        //sircl.addRequestHandler("onError", function (req) {
        //    req.$finalTarget = sircl.ext.$mainTarget();
        //    req.responseText = "<h1>Error " + req.status + " - " + (req.statusText || "Unexpected error") + "</h1><p>An unexpected error has occured.</p>";
        //    req.succeeded = true;
        //    this.next(req);
        //});
        sircl.addRequestHandler("onError", function (req) {
//            if (req.method === "get") {
                // Re-issue the request by the browser, to render the error page:
                //window.location.href = req.action
                //req.succeeded = true;
                //} else {
                // If no get request, we can not re-issue, then inform user:
                alert("An error has occured.");
//            }
            //console.log(req);
            //console.log(JSON.stringify(req));
            this.next(req);
            //;
        });
    </script>
    <script>

        sircl.addAttributeAlias(".bgblue", "style", "background-color: blue; color: white;", true);
        sircl.addAttributeAlias(".bordered", "style", "border: solid 3px black;", true);


    </script>

</body>
</html>